package systems.pkt.lingon.ui

object TestTags {
    const val TopBarTitle = "topbar_title"
    const val TopBarMenuButton = "topbar_menu"
    const val TopBarMenu = "topbar_menu_popup"
    const val ReloadButton = "reload_button"
    const val EndpointButton = "endpoint_button"
    const val EndpointInput = "endpoint_input"
    const val EndpointSave = "endpoint_save"
    const val ThemeButton = "theme_button"
    const val ThemeDialog = "theme_dialog"
    const val CopyAllButton = "copy_all_button"
    const val ZoomButton = "zoom_button"
    const val AppLockTimeoutButton = "app_lock_timeout_button"
    const val ZoomResetButton = "zoom_reset_button"
    const val ZoomSlider = "zoom_slider"
    const val ZoomSave = "zoom_save"
    const val ZoomValue = "zoom_value"
    const val LogoutButton = "logout_button"
    const val ShareTokenInput = "share_token_input"
    const val ShareTokenAttach = "share_token_attach"
    const val ShareTokenError = "share_token_error"
    const val ShareTokenButton = "share_token_button"
    const val CertificatesButton = "certificates_button"
    const val ResizeHostMenuItem = "resize_host_menu_item"
    const val ResizeHostToggle = "resize_host_toggle"
    const val BackgroundWallMenuItem = "background_wall_menu_item"
    const val BackgroundWallToggle = "background_wall_toggle"

    const val LoginUsername = "login_username"
    const val LoginPassword = "login_password"
    const val LoginTotp = "login_totp"
    const val LoginSubmit = "login_submit"
    const val LoginError = "login_error"

    const val TerminalInput = "terminal_input"
    const val TerminalSpinner = "terminal_spinner"
    const val TerminalList = "terminal_list"
    const val TerminalDebug = "terminal_debug"
    const val TerminalFocus = "terminal_focus"
    const val TabList = "tab_list"
    const val StatusBanner = "status_banner"
    const val StatusDismiss = "status_dismiss"
    const val RotateSSHKeyInput = "rotatesshkey_input"
    const val RotateSSHKeyConfirm = "rotatesshkey_confirm"
    const val RotateSSHKeyCancel = "rotatesshkey_cancel"
    const val AppLockTimeoutDialog = "app_lock_timeout_dialog"

    fun tabTag(label: String): String = "tab_$label"
}
