version: "2"
linters:
  exclusions:
    rules:
      # errcheck noise we explicitly accept for now
      - linters: [errcheck]
        path: ".*_test\\.go"
      - linters: [errcheck]
        text: "resp.Body.Close"
      - linters: [errcheck]
        text: "fmt.Fprint"
      # staticcheck style nits we don't want to chase
      - linters: [staticcheck]
        text: "QF1003"
      - linters: [staticcheck]
        text: "S1017"
      - linters: [staticcheck]
        text: "QF1001"
      - linters: [staticcheck]
        text: "S1009"
