apiVersion: v1
kind: Pod
metadata:
  name: lingon
  annotations:
    io.podman.annotations.userns: keep-id
spec:
  restartPolicy: Always
  containers:
    - name: lingon
      image: docker.io/pktsystems/lingon:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: LOG_MODE
          value: json
        - name: LOG_LEVEL
          value: debug
      args:
        - -c
        - /lingon/.lingon/config.yaml
        - serve
      ports:
        - containerPort: 12843
          hostPort: 12843
          protocol: TCP
      volumeMounts:
        - name: lingon-config
          mountPath: /lingon/.lingon
  volumes:
    - name: lingon-config
      hostPath:
        path: ${HOME}/.lingon
        type: DirectoryOrCreate
