// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/protocolpb/relay.proto

package protocolpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Frame struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Seq       uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Frame_Hello
	//	*Frame_Welcome
	//	*Frame_Snapshot
	//	*Frame_Diff
	//	*Frame_Out
	//	*Frame_In
	//	*Frame_Resize
	//	*Frame_Control
	//	*Frame_Error
	Payload       isFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_internal_protocolpb_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocolpb_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_internal_protocolpb_relay_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Frame) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Frame) GetPayload() isFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Frame) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Frame) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *Frame) GetSnapshot() *Snapshot {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *Frame) GetDiff() *Diff {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Diff); ok {
			return x.Diff
		}
	}
	return nil
}

func (x *Frame) GetOut() *Out {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Out); ok {
			return x.Out
		}
	}
	return nil
}

func (x *Frame) GetIn() *In {
	if x != nil {
		if x, ok := x.Payload.(*Frame_In); ok {
			return x.In
		}
	}
	return nil
}

func (x *Frame) GetResize() *Resize {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *Frame) GetControl() *Control {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Control); ok {
			return x.Control
		}
	}
	return nil
}

func (x *Frame) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isFrame_Payload interface {
	isFrame_Payload()
}

type Frame_Hello struct {
	Hello *Hello `protobuf:"bytes,10,opt,name=hello,proto3,oneof"`
}

type Frame_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,11,opt,name=welcome,proto3,oneof"`
}

type Frame_Snapshot struct {
	Snapshot *Snapshot `protobuf:"bytes,12,opt,name=snapshot,proto3,oneof"`
}

type Frame_Diff struct {
	Diff *Diff `protobuf:"bytes,13,opt,name=diff,proto3,oneof"`
}

type Frame_Out struct {
	Out *Out `protobuf:"bytes,14,opt,name=out,proto3,oneof"`
}

type Frame_In struct {
	In *In `protobuf:"bytes,15,opt,name=in,proto3,oneof"`
}

type Frame_Resize struct {
	Resize *Resize `protobuf:"bytes,16,opt,name=resize,proto3,oneof"`
}

type Frame_Control struct {
	Control *Control `protobuf:"bytes,17,opt,name=control,proto3,oneof"`
}

type Frame_Error struct {
	Error *Error `protobuf:"bytes,18,opt,name=error,proto3,oneof"`
}

func (*Frame_Hello) isFrame_Payload() {}

func (*Frame_Welcome) isFrame_Payload() {}

func (*Frame_Snapshot) isFrame_Payload() {}

func (*Frame_Diff) isFrame_Payload() {}

func (*Frame_Out) isFrame_Payload() {}

func (*Frame_In) isFrame_Payload() {}

func (*Frame_Resize) isFrame_Payload() {}

func (*Frame_Control) isFrame_Payload() {}

func (*Frame_Error) isFrame_Payload() {}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	WantsControl  bool                   `protobuf:"varint,4,opt,name=wants_control,json=wantsControl,proto3" json:"wants_control,omitempty"`
	LastSeq       uint64                 `protobuf:"varint,5,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	ClientType    string                 `protobuf:"bytes,6,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_internal_protocolpb_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocolpb_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_internal_protocolpb_relay_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Hello) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Hello) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Hello) GetWantsControl() bool {
	if x != nil {
		return x.WantsControl
	}
	return false
}

func (x *Hello) GetLastSeq() uint64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *Hello) GetClientType() string {
	if x != nil {
		return x.ClientType
	}
	return ""
}

type Welcome struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GrantedControl bool                   `protobuf:"varint,1,opt,name=granted_control,json=grantedControl,proto3" json:"granted_control,omitempty"`
	ServerCols     uint32                 `protobuf:"varint,2,opt,name=server_cols,json=serverCols,proto3" json:"server_cols,omitempty"`
	ServerRows     uint32                 `protobuf:"varint,3,opt,name=server_rows,json=serverRows,proto3" json:"server_rows,omitempty"`
	HolderClientId string                 `protobuf:"bytes,4,opt,name=holder_client_id,json=holderClientId,proto3" json:"holder_client_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_internal_protocolpb_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocolpb_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_internal_protocolpb_relay_proto_rawDescGZIP(), []int{2}
}

func (x *Welcome) GetGrantedControl() bool {
	if x != nil {
		return x.GrantedControl
	}
	return false
}

func (x *Welcome) GetServerCols() uint32 {
	if x != nil {
		return x.ServerCols
	}
	return 0
}

func (x *Welcome) GetServerRows() uint32 {
	if x != nil {
		return x.ServerRows
	}
	return 0
}

func (x *Welcome) GetHolderClientId() string {
	if x != nil {
		return x.HolderClientId
	}
	return ""
}

type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Runes         []uint32               `protobuf:"varint,3,rep,packed,name=runes,proto3" json:"runes,omitempty"`
	Modes         []int32                `protobuf:"varint,4,rep,packed,name=modes,proto3" json:"modes,omitempty"`
	Fg            []uint32               `protobuf:"varint,5,rep,packed,name=fg,proto3" json:"fg,omitempty"`
	Bg            []uint32               `protobuf:"varint,6,rep,packed,name=bg,proto3" json:"bg,omitempty"`
	Cursor        *Cursor                `protobuf:"bytes,7,opt,name=cursor,proto3" json:"cursor,omitempty"`
	CursorVisible bool                   `protobuf:"varint,8,opt,name=cursor_visible,json=cursorVisible,proto3" json:"cursor_visible,omitempty"`
	Mode          uint32                 `protobuf:"varint,9,opt,name=mode,proto3" json:"mode,omitempty"`
	Title         string                 `protobuf:"bytes,10,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_internal_protocolpb_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocolpb_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_internal_protocolpb_relay_proto_rawDescGZIP(), []int{3}
}

func (x *Snapshot) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Snapshot) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Snapshot) GetRunes() []uint32 {
	if x != nil {
		return x.Runes
	}
	return nil
}

func (x *Snapshot) GetModes() []int32 {
	if x != nil {
		return x.Modes
	}
	return nil
}

func (x *Snapshot) GetFg() []uint32 {
	if x != nil {
		return x.Fg
	}
	return nil
}

func (x *Snapshot) GetBg() []uint32 {
	if x != nil {
		return x.Bg
	}
	return nil
}

func (x *Snapshot) GetCursor() *Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *Snapshot) GetCursorVisible() bool {
	if x != nil {
		return x.CursorVisible
	}
	return false
}

func (x *Snapshot) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *Snapshot) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type DiffRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           uint32                 `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Runes         []uint32               `protobuf:"varint,2,rep,packed,name=runes,proto3" json:"runes,omitempty"`
	Modes         []int32                `protobuf:"varint,3,rep,packed,name=modes,proto3" json:"modes,omitempty"`
	Fg            []uint32               `protobuf:"varint,4,rep,packed,name=fg,proto3" json:"fg,omitempty"`
	Bg            []uint32               `protobuf:"varint,5,rep,packed,name=bg,proto3" json:"bg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffRow) Reset() {
	*x = DiffRow{}
	mi := &file_internal_protocolpb_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffRow) ProtoMessage() {}

func (x *DiffRow) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocolpb_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffRow.ProtoReflect.Descriptor instead.
func (*DiffRow) Descriptor() ([]byte, []int) {
	return file_internal_protocolpb_relay_proto_rawDescGZIP(), []int{4}
}

func (x *DiffRow) GetRow() uint32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *DiffRow) GetRunes() []uint32 {
	if x != nil {
		return x.Runes
	}
	return nil
}

func (x *DiffRow) GetModes() []int32 {
	if x != nil {
		return x.Modes
	}
	return nil
}

func (x *DiffRow) GetFg() []uint32 {
	if x != nil {
		return x.Fg
	}
	return nil
}

func (x *DiffRow) GetBg() []uint32 {
	if x != nil {
		return x.Bg
	}
	return nil
}

type Diff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	DiffRows      []*DiffRow             `protobuf:"bytes,3,rep,name=diff_rows,json=diffRows,proto3" json:"diff_rows,omitempty"`
	Cursor        *Cursor                `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	CursorVisible bool                   `protobuf:"varint,5,opt,name=cursor_visible,json=cursorVisible,proto3" json:"cursor_visible,omitempty"`
	Mode          uint32                 `protobuf:"varint,6,opt,name=mode,proto3" json:"mode,omitempty"`
	Title         string                 `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diff) Reset() {
	*x = Diff{}
	mi := &file_internal_protocolpb_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diff) ProtoMessage() {}

func (x *Diff) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocolpb_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diff.ProtoReflect.Descriptor instead.
func (*Diff) Descriptor() ([]byte, []int) {
	return file_internal_protocolpb_relay_proto_rawDescGZIP(), []int{5}
}

func (x *Diff) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Diff) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Diff) GetDiffRows() []*DiffRow {
	if x != nil {
		return x.DiffRows
	}
	return nil
}

func (x *Diff) GetCursor() *Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *Diff) GetCursorVisible() bool {
	if x != nil {
		return x.CursorVisible
	}
	return false
}

func (x *Diff) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *Diff) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type Out struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Out) Reset() {
	*x = Out{}
	mi := &file_internal_protocolpb_relay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Out) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out) ProtoMessage() {}

func (x *Out) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocolpb_relay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out.ProtoReflect.Descriptor instead.
func (*Out) Descriptor() ([]byte, []int) {
	return file_internal_protocolpb_relay_proto_rawDescGZIP(), []int{6}
}

func (x *Out) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type In struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *In) Reset() {
	*x = In{}
	mi := &file_internal_protocolpb_relay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *In) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In) ProtoMessage() {}

func (x *In) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocolpb_relay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In.ProtoReflect.Descriptor instead.
func (*In) Descriptor() ([]byte, []int) {
	return file_internal_protocolpb_relay_proto_rawDescGZIP(), []int{7}
}

func (x *In) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Resize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resize) Reset() {
	*x = Resize{}
	mi := &file_internal_protocolpb_relay_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resize) ProtoMessage() {}

func (x *Resize) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocolpb_relay_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resize.ProtoReflect.Descriptor instead.
func (*Resize) Descriptor() ([]byte, []int) {
	return file_internal_protocolpb_relay_proto_rawDescGZIP(), []int{8}
}

func (x *Resize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Resize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type Control struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HolderClientId string                 `protobuf:"bytes,1,opt,name=holder_client_id,json=holderClientId,proto3" json:"holder_client_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Control) Reset() {
	*x = Control{}
	mi := &file_internal_protocolpb_relay_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Control) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Control) ProtoMessage() {}

func (x *Control) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocolpb_relay_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Control.ProtoReflect.Descriptor instead.
func (*Control) Descriptor() ([]byte, []int) {
	return file_internal_protocolpb_relay_proto_rawDescGZIP(), []int{9}
}

func (x *Control) GetHolderClientId() string {
	if x != nil {
		return x.HolderClientId
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_internal_protocolpb_relay_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocolpb_relay_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_internal_protocolpb_relay_proto_rawDescGZIP(), []int{10}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Cursor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             uint32                 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             uint32                 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cursor) Reset() {
	*x = Cursor{}
	mi := &file_internal_protocolpb_relay_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cursor) ProtoMessage() {}

func (x *Cursor) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocolpb_relay_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cursor.ProtoReflect.Descriptor instead.
func (*Cursor) Descriptor() ([]byte, []int) {
	return file_internal_protocolpb_relay_proto_rawDescGZIP(), []int{11}
}

func (x *Cursor) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Cursor) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_internal_protocolpb_relay_proto protoreflect.FileDescriptor

const file_internal_protocolpb_relay_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/protocolpb/relay.proto\x12\x0flingon.protocol\"\xf9\x03\n" +
	"\x05Frame\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12.\n" +
	"\x05hello\x18\n" +
	" \x01(\v2\x16.lingon.protocol.HelloH\x00R\x05hello\x124\n" +
	"\awelcome\x18\v \x01(\v2\x18.lingon.protocol.WelcomeH\x00R\awelcome\x127\n" +
	"\bsnapshot\x18\f \x01(\v2\x19.lingon.protocol.SnapshotH\x00R\bsnapshot\x12+\n" +
	"\x04diff\x18\r \x01(\v2\x15.lingon.protocol.DiffH\x00R\x04diff\x12(\n" +
	"\x03out\x18\x0e \x01(\v2\x14.lingon.protocol.OutH\x00R\x03out\x12%\n" +
	"\x02in\x18\x0f \x01(\v2\x13.lingon.protocol.InH\x00R\x02in\x121\n" +
	"\x06resize\x18\x10 \x01(\v2\x17.lingon.protocol.ResizeH\x00R\x06resize\x124\n" +
	"\acontrol\x18\x11 \x01(\v2\x18.lingon.protocol.ControlH\x00R\acontrol\x12.\n" +
	"\x05error\x18\x12 \x01(\v2\x16.lingon.protocol.ErrorH\x00R\x05errorB\t\n" +
	"\apayload\"\xad\x01\n" +
	"\x05Hello\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\rR\x04rows\x12#\n" +
	"\rwants_control\x18\x04 \x01(\bR\fwantsControl\x12\x19\n" +
	"\blast_seq\x18\x05 \x01(\x04R\alastSeq\x12\x1f\n" +
	"\vclient_type\x18\x06 \x01(\tR\n" +
	"clientType\"\x9e\x01\n" +
	"\aWelcome\x12'\n" +
	"\x0fgranted_control\x18\x01 \x01(\bR\x0egrantedControl\x12\x1f\n" +
	"\vserver_cols\x18\x02 \x01(\rR\n" +
	"serverCols\x12\x1f\n" +
	"\vserver_rows\x18\x03 \x01(\rR\n" +
	"serverRows\x12(\n" +
	"\x10holder_client_id\x18\x04 \x01(\tR\x0eholderClientId\"\x90\x02\n" +
	"\bSnapshot\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\x12\x18\n" +
	"\x05runes\x18\x03 \x03(\rB\x02\x10\x01R\x05runes\x12\x18\n" +
	"\x05modes\x18\x04 \x03(\x05B\x02\x10\x01R\x05modes\x12\x12\n" +
	"\x02fg\x18\x05 \x03(\rB\x02\x10\x01R\x02fg\x12\x12\n" +
	"\x02bg\x18\x06 \x03(\rB\x02\x10\x01R\x02bg\x12/\n" +
	"\x06cursor\x18\a \x01(\v2\x17.lingon.protocol.CursorR\x06cursor\x12%\n" +
	"\x0ecursor_visible\x18\b \x01(\bR\rcursorVisible\x12\x12\n" +
	"\x04mode\x18\t \x01(\rR\x04mode\x12\x14\n" +
	"\x05title\x18\n" +
	" \x01(\tR\x05title\"w\n" +
	"\aDiffRow\x12\x10\n" +
	"\x03row\x18\x01 \x01(\rR\x03row\x12\x18\n" +
	"\x05runes\x18\x02 \x03(\rB\x02\x10\x01R\x05runes\x12\x18\n" +
	"\x05modes\x18\x03 \x03(\x05B\x02\x10\x01R\x05modes\x12\x12\n" +
	"\x02fg\x18\x04 \x03(\rB\x02\x10\x01R\x02fg\x12\x12\n" +
	"\x02bg\x18\x05 \x03(\rB\x02\x10\x01R\x02bg\"\xe7\x01\n" +
	"\x04Diff\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\x125\n" +
	"\tdiff_rows\x18\x03 \x03(\v2\x18.lingon.protocol.DiffRowR\bdiffRows\x12/\n" +
	"\x06cursor\x18\x04 \x01(\v2\x17.lingon.protocol.CursorR\x06cursor\x12%\n" +
	"\x0ecursor_visible\x18\x05 \x01(\bR\rcursorVisible\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\rR\x04mode\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\"\x19\n" +
	"\x03Out\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x18\n" +
	"\x02In\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"0\n" +
	"\x06Resize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"3\n" +
	"\aControl\x12(\n" +
	"\x10holder_client_id\x18\x01 \x01(\tR\x0eholderClientId\"!\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"$\n" +
	"\x06Cursor\x12\f\n" +
	"\x01x\x18\x01 \x01(\rR\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\rR\x01yB3Z1pkt.systems/lingon/internal/protocolpb;protocolpbb\x06proto3"

var (
	file_internal_protocolpb_relay_proto_rawDescOnce sync.Once
	file_internal_protocolpb_relay_proto_rawDescData []byte
)

func file_internal_protocolpb_relay_proto_rawDescGZIP() []byte {
	file_internal_protocolpb_relay_proto_rawDescOnce.Do(func() {
		file_internal_protocolpb_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocolpb_relay_proto_rawDesc), len(file_internal_protocolpb_relay_proto_rawDesc)))
	})
	return file_internal_protocolpb_relay_proto_rawDescData
}

var file_internal_protocolpb_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_protocolpb_relay_proto_goTypes = []any{
	(*Frame)(nil),    // 0: lingon.protocol.Frame
	(*Hello)(nil),    // 1: lingon.protocol.Hello
	(*Welcome)(nil),  // 2: lingon.protocol.Welcome
	(*Snapshot)(nil), // 3: lingon.protocol.Snapshot
	(*DiffRow)(nil),  // 4: lingon.protocol.DiffRow
	(*Diff)(nil),     // 5: lingon.protocol.Diff
	(*Out)(nil),      // 6: lingon.protocol.Out
	(*In)(nil),       // 7: lingon.protocol.In
	(*Resize)(nil),   // 8: lingon.protocol.Resize
	(*Control)(nil),  // 9: lingon.protocol.Control
	(*Error)(nil),    // 10: lingon.protocol.Error
	(*Cursor)(nil),   // 11: lingon.protocol.Cursor
}
var file_internal_protocolpb_relay_proto_depIdxs = []int32{
	1,  // 0: lingon.protocol.Frame.hello:type_name -> lingon.protocol.Hello
	2,  // 1: lingon.protocol.Frame.welcome:type_name -> lingon.protocol.Welcome
	3,  // 2: lingon.protocol.Frame.snapshot:type_name -> lingon.protocol.Snapshot
	5,  // 3: lingon.protocol.Frame.diff:type_name -> lingon.protocol.Diff
	6,  // 4: lingon.protocol.Frame.out:type_name -> lingon.protocol.Out
	7,  // 5: lingon.protocol.Frame.in:type_name -> lingon.protocol.In
	8,  // 6: lingon.protocol.Frame.resize:type_name -> lingon.protocol.Resize
	9,  // 7: lingon.protocol.Frame.control:type_name -> lingon.protocol.Control
	10, // 8: lingon.protocol.Frame.error:type_name -> lingon.protocol.Error
	11, // 9: lingon.protocol.Snapshot.cursor:type_name -> lingon.protocol.Cursor
	4,  // 10: lingon.protocol.Diff.diff_rows:type_name -> lingon.protocol.DiffRow
	11, // 11: lingon.protocol.Diff.cursor:type_name -> lingon.protocol.Cursor
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_internal_protocolpb_relay_proto_init() }
func file_internal_protocolpb_relay_proto_init() {
	if File_internal_protocolpb_relay_proto != nil {
		return
	}
	file_internal_protocolpb_relay_proto_msgTypes[0].OneofWrappers = []any{
		(*Frame_Hello)(nil),
		(*Frame_Welcome)(nil),
		(*Frame_Snapshot)(nil),
		(*Frame_Diff)(nil),
		(*Frame_Out)(nil),
		(*Frame_In)(nil),
		(*Frame_Resize)(nil),
		(*Frame_Control)(nil),
		(*Frame_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocolpb_relay_proto_rawDesc), len(file_internal_protocolpb_relay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protocolpb_relay_proto_goTypes,
		DependencyIndexes: file_internal_protocolpb_relay_proto_depIdxs,
		MessageInfos:      file_internal_protocolpb_relay_proto_msgTypes,
	}.Build()
	File_internal_protocolpb_relay_proto = out.File
	file_internal_protocolpb_relay_proto_goTypes = nil
	file_internal_protocolpb_relay_proto_depIdxs = nil
}
